load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_nasm//nasm:defs.bzl", "nasm_library")
load("//:ffmpeg.bzl", "CC_COPTS", "ffmpeg_cc_test")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

nasm_library(
    name = "avcodec_asm_clean",
    srcs = [
        "x86/blockdsp.asm",
        "x86/bswapdsp.asm",
        "x86/celt_pvq_search.asm",
        "x86/fpel.asm",
        "x86/h264_chromamc.asm",
        "x86/h264_chromamc_10bit.asm",
        "x86/h264_deblock.asm",
        "x86/h264_deblock_10bit.asm",
        "x86/h264_idct.asm",
        "x86/h264_idct_10bit.asm",
        "x86/h264_intrapred.asm",
        "x86/h264_intrapred_10bit.asm",
        "x86/h264_qpel_10bit.asm",
        "x86/h264_qpel_8bit.asm",
        "x86/h264_weight.asm",
        "x86/h264_weight_10bit.asm",
        "x86/h26x/h2656_inter.asm",
        "x86/hevc/add_res.asm",
        "x86/hevc/deblock.asm",
        "x86/hevc/idct.asm",
        "x86/hevc/mc.asm",
        "x86/hevc/sao.asm",
        "x86/hevc/sao_10bit.asm",
        "x86/hpeldsp.asm",
        "x86/idctdsp.asm",
        "x86/me_cmp.asm",
        "x86/opusdsp.asm",
        "x86/qpel.asm",
        "x86/qpeldsp.asm",
        "x86/simple_idct.asm",
        "x86/simple_idct10.asm",
        "x86/vc1dsp_loopfilter.asm",
        "x86/vc1dsp_mc.asm",
        "x86/videodsp.asm",
        "x86/xvididct.asm",
    ],
    hdrs = [
        "x86/aacencdsp.asm",
        "x86/aacpsdsp.asm",
        "x86/ac3dsp.asm",
        "x86/ac3dsp_downmix.asm",
        "x86/alacdsp.asm",
        "x86/apv_dsp.asm",
        "x86/audiodsp.asm",
        "x86/blockdsp.asm",
        "x86/bswapdsp.asm",
        "x86/cavs_qpel.asm",
        "x86/cavsidct.asm",
        "x86/celt_pvq_search.asm",
        "x86/cfhddsp.asm",
        "x86/cfhdencdsp.asm",
        "x86/dcadsp.asm",
        "x86/dct32.asm",
        "x86/dirac_dwt.asm",
        "x86/diracdsp.asm",
        "x86/dnxhdenc.asm",
        "x86/exrdsp.asm",
        "x86/flac_dsp_gpl.asm",  # GPL
        "x86/flacdsp.asm",
        "x86/fmtconvert.asm",
        "x86/fpel.asm",
        "x86/g722dsp.asm",
        "x86/h263_loopfilter.asm",
        "x86/h264_chromamc.asm",
        "x86/h264_chromamc_10bit.asm",
        "x86/h264_deblock.asm",
        "x86/h264_deblock_10bit.asm",
        "x86/h264_idct.asm",
        "x86/h264_idct_10bit.asm",
        "x86/h264_intrapred.asm",
        "x86/h264_intrapred_10bit.asm",
        "x86/h264_qpel_10bit.asm",
        "x86/h264_qpel_8bit.asm",
        "x86/h264_weight.asm",
        "x86/h264_weight_10bit.asm",
        "x86/h26x/h2656_inter.asm",
        "x86/h26x/h2656_sao.asm",
        "x86/h26x/h2656_sao_10bit.asm",
        "x86/hevc/add_res.asm",
        "x86/hevc/deblock.asm",
        "x86/hevc/idct.asm",
        "x86/hevc/mc.asm",
        "x86/hevc/sao.asm",
        "x86/hevc/sao_10bit.asm",
        "x86/hpeldsp.asm",
        "x86/huffyuvdsp.asm",
        "x86/huffyuvdsp_template.asm",
        "x86/huffyuvencdsp.asm",
        "x86/idctdsp.asm",
        "x86/imdct36.asm",
        "x86/jpeg2000dsp.asm",
        "x86/lossless_audiodsp.asm",
        "x86/lossless_videodsp.asm",
        "x86/lossless_videoencdsp.asm",
        "x86/lpc.asm",
        "x86/me_cmp.asm",
        "x86/mlpdsp.asm",
        "x86/mpegvideoencdsp.asm",
        "x86/opusdsp.asm",
        "x86/pixblockdsp.asm",
        "x86/pngdsp.asm",
        "x86/proresdsp.asm",
        "x86/qpel.asm",
        "x86/qpeldsp.asm",
        "x86/rv34dsp.asm",
        "x86/rv40dsp.asm",
        "x86/sbcdsp.asm",
        "x86/sbrdsp.asm",
        "x86/simple_idct.asm",
        "x86/simple_idct10.asm",
        "x86/simple_idct10_template.asm",
        "x86/svq1enc.asm",
        "x86/synth_filter.asm",
        "x86/takdsp.asm",
        "x86/ttadsp.asm",
        "x86/ttaencdsp.asm",
        "x86/utvideodsp.asm",
        "x86/v210.asm",
        "x86/v210enc.asm",
        "x86/vc1dsp_loopfilter.asm",
        "x86/vc1dsp_mc.asm",
        "x86/videodsp.asm",
        "x86/vorbisdsp.asm",
        "x86/vp3dsp.asm",
        "x86/vp6dsp.asm",
        "x86/vp8dsp.asm",
        "x86/vp8dsp_loopfilter.asm",
        "x86/vp9intrapred.asm",
        "x86/vp9intrapred_16bpp.asm",
        "x86/vp9itxfm.asm",
        "x86/vp9itxfm_16bpp.asm",
        "x86/vp9itxfm_16bpp_avx512.asm",
        "x86/vp9itxfm_avx2.asm",
        "x86/vp9itxfm_avx512.asm",
        "x86/vp9itxfm_template.asm",
        "x86/vp9lpf.asm",
        "x86/vp9lpf_16bpp.asm",
        "x86/vp9mc.asm",
        "x86/vp9mc_16bpp.asm",
        "x86/vvc/alf.asm",
        "x86/vvc/dmvr.asm",
        "x86/vvc/mc.asm",
        "x86/vvc/of.asm",
        "x86/vvc/sad.asm",
        "x86/vvc/sao.asm",
        "x86/vvc/sao_10bit.asm",
        "x86/xvididct.asm",
        "//libavutil:x86/x86inc.asm",
        "//libavutil:x86/x86util.asm",
    ] + select({
        "//:linux_x86_64": [
            "//:platform/linux-x86_64/config.asm",
            "//:platform/linux-x86_64/config_components.asm",
        ],
        "//:windows_x86_64": [
            "//:platform/windows-x86_64/config.asm",
            "//:platform/windows-x86_64/config_components.asm",
        ],
        "//conditions:default": [],
    }),
    copts = select({
        "//:windows_x86_64": [
            "-f",
            "win64",
            "-DPIC",
        ],
        "//conditions:default": [
            "-f",
            "elf64",
            "-DPIC",
        ],
    }),
    includes = [
        ".",
        "..",
        "x86",
        "//libavutil:x86",
        "//libswresample:x86",
        "//libswscale:x86",
    ] + select({
        "//:linux_x86_64": ["../platform/linux-x86_64"],
        "//:linux_aarch64": ["../platform/linux-aarch64"],
        "//:darwin_aarch64": ["../platform/darwin-aarch64"],
        "//:windows_x86_64": ["../platform/windows-x86_64"],
        "//conditions:default": [],
    }),
    preincs = select({
        "//:linux_x86_64": ["//:platform/linux-x86_64/config.asm"],
        "//:windows_x86_64": ["//:platform/windows-x86_64/config.asm"],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "avcodec",
    srcs = [
        "aac_ac3_parser.c",
        "aac_parser.c",
        "ac3_channel_layout_tab.c",
        "ac3_parser.c",
        "ac3tab.c",
        "adts_header.c",
        "adts_parser.c",
        "adx_parser.c",
        "ahx_parser.c",
        "allcodecs.c",
        "amr_parser.c",
        "aom_film_grain.c",
        "apv_parser.c",
        "atsc_a53.c",
        "audio_frame_queue.c",
        "av1_parse.c",
        "av1_parser.c",
        "avcodec.c",
        "avdct.c",
        "avs2.c",
        "avs2_parser.c",
        "avs3_parser.c",
        "bitstream.c",
        "bitstream_filters.c",
        "blockdsp.c",
        "bmp_parser.c",
        "bsf.c",
        "bsf/aac_adtstoasc.c",
        "bsf/ahx_to_mp2.c",
        "bsf/apv_metadata.c",
        "bsf/av1_frame_merge.c",
        "bsf/av1_frame_split.c",
        "bsf/av1_metadata.c",
        "bsf/chomp.c",
        "bsf/dca_core.c",
        "bsf/dovi_rpu.c",
        "bsf/dts2pts.c",
        "bsf/dump_extradata.c",
        "bsf/dv_error_marker.c",
        "bsf/eac3_core.c",
        "bsf/eia608_to_smpte436m.c",
        "bsf/evc_frame_merge.c",
        "bsf/extract_extradata.c",
        "bsf/filter_units.c",
        "bsf/h264_metadata.c",
        "bsf/h264_mp4toannexb.c",
        "bsf/h264_redundant_pps.c",
        "bsf/h265_metadata.c",
        "bsf/h266_metadata.c",
        "bsf/hapqa_extract.c",
        "bsf/hevc_mp4toannexb.c",
        "bsf/imx_dump_header.c",
        "bsf/media100_to_mjpegb.c",
        "bsf/mjpeg2jpeg.c",
        "bsf/mjpega_dump_header.c",
        "bsf/movsub.c",
        "bsf/mpeg2_metadata.c",
        "bsf/mpeg4_unpack_bframes.c",
        "bsf/noise.c",
        "bsf/null.c",
        "bsf/opus_metadata.c",
        "bsf/pcm_rechunk.c",
        "bsf/pgs_frame_merge.c",
        "bsf/prores_metadata.c",
        "bsf/remove_extradata.c",
        "bsf/setts.c",
        "bsf/showinfo.c",
        "bsf/smpte436m_to_eia608.c",
        "bsf/trace_headers.c",
        "bsf/truehd_core.c",
        "bsf/vp9_metadata.c",
        "bsf/vp9_raw_reorder.c",
        "bsf/vp9_superframe.c",
        "bsf/vp9_superframe_split.c",
        "bsf/vvc_mp4toannexb.c",
        "bswapdsp.c",
        "cabac.c",
        "cavs_parser.c",
        "cbs.c",
        "cbs_apv.c",
        "cbs_av1.c",
        "cbs_bsf.c",
        "cbs_h2645.c",
        "cbs_mpeg2.c",
        "cbs_sei.c",
        "cbs_vp8.c",
        "cbs_vp9.c",
        "celp_math.c",
        "codec_desc.c",
        "codec_par.c",
        "cook_parser.c",
        "cri_parser.c",
        "dca.c",
        "dca_exss.c",
        "dca_parser.c",
        "dca_sample_rate_tab.c",
        "dctref.c",
        "decode.c",
        "dirac.c",
        "dirac_parser.c",
        "dnxhd_parser.c",
        "dnxhddata.c",
        "dnxuc_parser.c",
        "dolby_e_parse.c",
        "dolby_e_parser.c",
        "dovi_rpu.c",
        "dovi_rpudec.c",
        "dovi_rpuenc.c",
        "dpx_parser.c",
        "dv_profile.c",
        "dvaudio_parser.c",
        "dvbsub_parser.c",
        "dvd_nav_parser.c",
        "dvdsub_parser.c",
        "dynamic_hdr_vivid.c",
        "encode.c",
        "error_resilience.c",
        "evc_parse.c",
        "evc_parser.c",
        "evc_ps.c",
        "exif.c",
        "faandct.c",
        "faanidct.c",
        "fdctdsp.c",
        "ffv1.c",
        "ffv1_parse.c",
        "ffv1_parser.c",
        "flac.c",
        "flac_parser.c",
        "flacdata.c",
        "float_scalarproduct.c",
        "frame_thread_encoder.c",
        "ftr_parser.c",
        "g723_1_parser.c",
        "g729_parser.c",
        "get_buffer.c",
        "gif.c",
        "gif_parser.c",
        "gifdec.c",
        "golomb.c",
        "gsm_parser.c",
        "h261_parser.c",
        "h263.c",
        "h263_parser.c",
        "h263data.c",
        "h2645_parse.c",
        "h2645_sei.c",
        "h2645_vui.c",
        "h2645data.c",
        "h264_cabac.c",
        "h264_cavlc.c",
        "h264_direct.c",
        "h264_levels.c",
        "h264_loopfilter.c",
        "h264_mb.c",
        "h264_parse.c",
        "h264_parser.c",
        "h264_picture.c",
        "h264_ps.c",
        "h264_refs.c",
        "h264_sei.c",
        "h264_slice.c",
        "h264chroma.c",
        "h264data.c",
        "h264dec.c",
        "h264dsp.c",
        "h264idct.c",
        "h264pred.c",
        "h264qpel.c",
        "h265_profile_level.c",
        "h274.c",
        "hap.c",
        "hdr_parser.c",
        "hevc/cabac.c",
        "hevc/data.c",
        "hevc/dsp.c",
        "hevc/filter.c",
        "hevc/hevcdec.c",
        "hevc/mvs.c",
        "hevc/parse.c",
        "hevc/parser.c",
        "hevc/pred.c",
        "hevc/ps.c",
        "hevc/refs.c",
        "hevc/sei.c",
        "hpeldsp.c",
        "idctdsp.c",
        "imgconvert.c",
        "ipu_parser.c",
        "ituh263dec.c",
        "jfdctfst.c",  # libjpeg
        "jfdctint.c",  # libjpeg
        "jni.c",
        "jpeg2000_parser.c",
        "jpegtables.c",
        "jpegxl_parse.c",
        "jpegxl_parser.c",
        "jpegxs_parser.c",
        "jrevdct.c",  # libjpeg
        "latm_parser.c",
        "libvpxdec.c",
        "libvpxenc.c",
        "log2_tab.c",
        "lzw.c",
        "lzwenc.c",
        "mathtables.c",
        "me_cmp.c",
        "mediacodec.c",
        "misc4_parser.c",
        "mjpeg_parser.c",
        "mlp.c",
        "mlp_parse.c",
        "mlp_parser.c",
        "mpeg12data.c",
        "mpeg12framerate.c",
        "mpeg4audio.c",
        "mpeg4audio_sample_rates.c",
        "mpeg4video.c",
        "mpeg4video_parser.c",
        "mpeg4videodec.c",
        "mpeg_er.c",
        "mpegaudio_parser.c",
        "mpegaudiodecheader.c",
        "mpegaudiotabs.c",
        "mpegpicture.c",
        "mpegutils.c",
        "mpegvideo.c",
        "mpegvideo_dec.c",
        "mpegvideo_motion.c",
        "mpegvideo_parser.c",
        "mpegvideo_unquantize.c",
        "mpegvideodata.c",
        "options.c",
        "opus/celt.c",
        "opus/dec.c",
        "opus/dec_celt.c",
        "opus/dsp.c",
        "opus/enc.c",
        "opus/enc_psy.c",
        "opus/parse.c",
        "opus/parser.c",
        "opus/pvq.c",
        "opus/rc.c",
        "opus/silk.c",
        "opus/tab.c",
        "packet.c",
        "parser.c",
        "parsers.c",
        "png_parser.c",
        "pnm.c",
        "pnm_parser.c",
        "profiles.c",
        "prores_parser.c",
        "prores_raw_parser.c",
        "pthread.c",
        "pthread_frame.c",
        "pthread_slice.c",
        "qoi_parser.c",
        "qsv_api.c",
        "rangecoder.c",
        "raw.c",
        "reverse.c",
        "rl.c",
        "rv34_parser.c",
        "sbc_parser.c",
        "simple_idct.c",
        "sipr_parser.c",
        "smpte_436m.c",
        "startcode.c",
        "tak.c",
        "tak_parser.c",
        "threadprogress.c",
        "tiff_common.c",
        "timecode_internal.c",
        "to_upper4.c",
        "utils.c",
        "vc1.c",
        "vc1_parser.c",
        "vc1data.c",
        "vc1dsp.c",
        "version.c",
        "videodsp.c",
        "vlc.c",
        "vorbis_data.c",
        "vorbis_parser.c",
        "vp3_parser.c",
        "vp8_parser.c",
        "vp8data.c",
        "vp9_parser.c",
        "vvc_parser.c",
        "webp_parser.c",
        "wmv2data.c",
    ] + select({
        "//:linux_x86_64": [
            "x86/blockdsp_init.c",
            "x86/bswapdsp_init.c",
            "x86/celt_pvq_init.c",
            "x86/constants.c",
            "x86/fdct.c",
            "x86/fdctdsp_init.c",
            "x86/h264_intrapred_init.c",
            "x86/h264_qpel.c",
            "x86/h264chroma_init.c",
            "x86/h264dsp_init.c",
            "x86/h26x/h2656dsp.c",
            "x86/hevc/dsp_init.c",
            "x86/hpeldsp_init.c",
            "x86/idctdsp_init.c",
            "x86/me_cmp_init.c",
            "x86/mpegvideo.c",
            "x86/opusdsp_init.c",
            "x86/qpeldsp_init.c",
            "x86/vc1dsp_init.c",
            "x86/vc1dsp_mmx.c",
            "x86/videodsp_init.c",
            "x86/xvididct_init.c",
            ":avcodec_asm_clean",
        ],
        "//:windows_x86_64": [
            "d3d11va.c",
            "d3d12va_decode.c",
            "dxva2.c",
            "x86/blockdsp_init.c",
            "x86/bswapdsp_init.c",
            "x86/celt_pvq_init.c",
            "x86/constants.c",
            "x86/fdct.c",
            "x86/fdctdsp_init.c",
            "x86/h264_intrapred_init.c",
            "x86/h264_qpel.c",
            "x86/h264chroma_init.c",
            "x86/h264dsp_init.c",
            "x86/h26x/h2656dsp.c",
            "x86/hevc/dsp_init.c",
            "x86/hpeldsp_init.c",
            "x86/idctdsp_init.c",
            "x86/me_cmp_init.c",
            "x86/mpegvideo.c",
            "x86/opusdsp_init.c",
            "x86/qpeldsp_init.c",
            "x86/vc1dsp_init.c",
            "x86/vc1dsp_mmx.c",
            "x86/videodsp_init.c",
            "x86/xvididct_init.c",
            ":avcodec_asm_clean",
        ],
        "//:linux_aarch64": [
            "aarch64/aacencdsp_init.c",
            "aarch64/aacencdsp_neon.S",
            "aarch64/aacpsdsp_init_aarch64.c",
            "aarch64/aacpsdsp_neon.S",
            "aarch64/ac3dsp_init_aarch64.c",
            "aarch64/ac3dsp_neon.S",
            "aarch64/fdctdsp_init_aarch64.c",
            "aarch64/fdctdsp_neon.S",
            "aarch64/fmtconvert_init.c",
            "aarch64/fmtconvert_neon.S",
            "aarch64/h264chroma_init_aarch64.c",
            "aarch64/h264cmc_neon.S",
            "aarch64/h264dsp_init_aarch64.c",
            "aarch64/h264dsp_neon.S",
            "aarch64/h264idct_neon.S",
            "aarch64/h264pred_init.c",
            "aarch64/h264pred_neon.S",
            "aarch64/h264qpel_init_aarch64.c",
            "aarch64/h264qpel_neon.S",
            "aarch64/h26x/epel_neon.S",
            "aarch64/h26x/qpel_neon.S",
            "aarch64/h26x/sao_neon.S",
            "aarch64/hevcdsp_deblock_neon.S",
            "aarch64/hevcdsp_dequant_neon.S",
            "aarch64/hevcdsp_idct_neon.S",
            "aarch64/hevcdsp_init_aarch64.c",
            "aarch64/hpeldsp_init_aarch64.c",
            "aarch64/hpeldsp_neon.S",
            "aarch64/idctdsp_init_aarch64.c",
            "aarch64/idctdsp_neon.S",
            "aarch64/me_cmp_init_aarch64.c",
            "aarch64/me_cmp_neon.S",
            "aarch64/mpegaudiodsp_init.c",
            "aarch64/mpegaudiodsp_neon.S",
            "aarch64/mpegvideoencdsp_init.c",
            "aarch64/mpegvideoencdsp_neon.S",
            "aarch64/neon.S",
            "aarch64/neontest.c",
            "aarch64/opusdsp_init.c",
            "aarch64/opusdsp_neon.S",
            "aarch64/pixblockdsp_init_aarch64.c",
            "aarch64/pixblockdsp_neon.S",
            "aarch64/rv40dsp_init_aarch64.c",
            "aarch64/sbrdsp_init_aarch64.c",
            "aarch64/sbrdsp_neon.S",
            "aarch64/simple_idct_neon.S",
            "aarch64/synth_filter_init.c",
            "aarch64/synth_filter_neon.S",
            "aarch64/vc1dsp_init_aarch64.c",
            "aarch64/vc1dsp_neon.S",
            "aarch64/videodsp.S",
            "aarch64/videodsp_init.c",
            "aarch64/vorbisdsp_init.c",
            "aarch64/vorbisdsp_neon.S",
            "aarch64/vp8dsp_init_aarch64.c",
            "aarch64/vp8dsp_neon.S",
            "aarch64/vp9dsp_init_10bpp_aarch64.c",
            "aarch64/vp9dsp_init_12bpp_aarch64.c",
            "aarch64/vp9dsp_init_aarch64.c",
            "aarch64/vp9itxfm_16bpp_neon.S",
            "aarch64/vp9itxfm_neon.S",
            "aarch64/vp9lpf_16bpp_neon.S",
            "aarch64/vp9lpf_neon.S",
            "aarch64/vp9mc_16bpp_neon.S",
            "aarch64/vp9mc_aarch64.S",
            "aarch64/vp9mc_neon.S",
            "aarch64/vvc/alf.S",
            "aarch64/vvc/dsp_init.c",
            "aarch64/vvc/inter.S",
            "aarch64/vvc/sad.S",
        ],
        "//:darwin_aarch64": [
            "aarch64/aacencdsp_init.c",
            "aarch64/aacencdsp_neon.S",
            "aarch64/aacpsdsp_init_aarch64.c",
            "aarch64/aacpsdsp_neon.S",
            "aarch64/ac3dsp_init_aarch64.c",
            "aarch64/ac3dsp_neon.S",
            "aarch64/fdctdsp_init_aarch64.c",
            "aarch64/fdctdsp_neon.S",
            "aarch64/fmtconvert_init.c",
            "aarch64/fmtconvert_neon.S",
            "aarch64/h264chroma_init_aarch64.c",
            "aarch64/h264cmc_neon.S",
            "aarch64/h264dsp_init_aarch64.c",
            "aarch64/h264dsp_neon.S",
            "aarch64/h264idct_neon.S",
            "aarch64/h264pred_init.c",
            "aarch64/h264pred_neon.S",
            "aarch64/h264qpel_init_aarch64.c",
            "aarch64/h264qpel_neon.S",
            "aarch64/h26x/epel_neon.S",
            "aarch64/h26x/qpel_neon.S",
            "aarch64/h26x/sao_neon.S",
            "aarch64/hevcdsp_deblock_neon.S",
            "aarch64/hevcdsp_dequant_neon.S",
            "aarch64/hevcdsp_idct_neon.S",
            "aarch64/hevcdsp_init_aarch64.c",
            "aarch64/hpeldsp_init_aarch64.c",
            "aarch64/hpeldsp_neon.S",
            "aarch64/idctdsp_init_aarch64.c",
            "aarch64/idctdsp_neon.S",
            "aarch64/me_cmp_init_aarch64.c",
            "aarch64/me_cmp_neon.S",
            "aarch64/mpegaudiodsp_init.c",
            "aarch64/mpegaudiodsp_neon.S",
            "aarch64/mpegvideoencdsp_init.c",
            "aarch64/mpegvideoencdsp_neon.S",
            "aarch64/neon.S",
            "aarch64/neontest.c",
            "aarch64/opusdsp_init.c",
            "aarch64/opusdsp_neon.S",
            "aarch64/pixblockdsp_init_aarch64.c",
            "aarch64/pixblockdsp_neon.S",
            "aarch64/rv40dsp_init_aarch64.c",
            "aarch64/sbrdsp_init_aarch64.c",
            "aarch64/sbrdsp_neon.S",
            "aarch64/simple_idct_neon.S",
            "aarch64/synth_filter_init.c",
            "aarch64/synth_filter_neon.S",
            "aarch64/vc1dsp_init_aarch64.c",
            "aarch64/vc1dsp_neon.S",
            "aarch64/videodsp.S",
            "aarch64/videodsp_init.c",
            "aarch64/vorbisdsp_init.c",
            "aarch64/vorbisdsp_neon.S",
            "aarch64/vp8dsp_init_aarch64.c",
            "aarch64/vp8dsp_neon.S",
            "aarch64/vp9dsp_init_10bpp_aarch64.c",
            "aarch64/vp9dsp_init_12bpp_aarch64.c",
            "aarch64/vp9dsp_init_aarch64.c",
            "aarch64/vp9itxfm_16bpp_neon.S",
            "aarch64/vp9itxfm_neon.S",
            "aarch64/vp9lpf_16bpp_neon.S",
            "aarch64/vp9lpf_neon.S",
            "aarch64/vp9mc_16bpp_neon.S",
            "aarch64/vp9mc_aarch64.S",
            "aarch64/vp9mc_neon.S",
            "aarch64/vvc/alf.S",
            "aarch64/vvc/dsp_init.c",
            "aarch64/vvc/inter.S",
            "aarch64/vvc/sad.S",
            "h263dec.c",
            "h263dsp.c",
            "mpeg4videodsp.c",
            "neon/mpegvideo.c",
            "videotoolbox.c",
            "videotoolbox_av1.c",
            "videotoolbox_vp9.c",
        ],
        "//conditions:default": [],
    }) + [
        "qpeldsp.c",
        "xbm_parser.c",
        "xiph.c",
        "xma_parser.c",
        "xvididct.c",
        "xwd_parser.c",
    ],
    hdrs = [
        "a64colors.h",
        "a64tables.h",
        "aac.h",
        "aac/aacdec.h",
        "aac/aacdec_ac.h",
        "aac/aacdec_fixed_coupling.h",
        "aac/aacdec_fixed_dequant.h",
        "aac/aacdec_fixed_prediction.h",
        "aac/aacdec_float_coupling.h",
        "aac/aacdec_float_prediction.h",
        "aac/aacdec_latm.h",
        "aac/aacdec_lpd.h",
        "aac/aacdec_tab.h",
        "aac/aacdec_usac.h",
        "aac_ac3_parser.h",
        "aac_defines.h",
        "aaccoder_trellis.h",
        "aaccoder_twoloop.h",
        "aacenc.h",
        "aacenc_is.h",
        "aacenc_quantization.h",
        "aacenc_quantization_misc.h",
        "aacenc_tns.h",
        "aacenc_utils.h",
        "aacencdsp.h",
        "aacenctab.h",
        "aacps.h",
        "aacps_fixed_tablegen.h",
        "aacps_tablegen.h",
        "aacpsdsp.h",
        "aacsbr.h",
        "aacsbrdata.h",
        "aactab.h",
        "aandcttab.h",
        "aarch64/cabac.h",
        "aarch64/fdct.h",
        "aarch64/h26x/dsp.h",
        "aarch64/idct.h",
        "aarch64/vp8dsp.h",
        "aarch64/vp9dsp_init.h",
        "ac3.h",
        "ac3_channel_layout_tab.h",
        "ac3_parser.h",
        "ac3_parser_internal.h",
        "ac3dec.h",
        "ac3dec_data.h",
        "ac3defs.h",
        "ac3dsp.h",
        "ac3enc.h",
        "ac3tab.h",
        "acelp_filters.h",
        "acelp_pitch_delay.h",
        "acelp_vectors.h",
        "adpcm.h",
        "adpcm_data.h",
        "adts_header.h",
        "adts_parser.h",
        "adx.h",
        "alac_data.h",
        "alacdsp.h",
        "amfdec.h",
        "amfenc.h",
        "amr.h",
        "amrnbdata.h",
        "amrwbdata.h",
        "aom_film_grain.h",
        "apng.h",
        "aptx.h",
        "apv.h",
        "apv_decode.h",
        "apv_dsp.h",
        "arm/aac.h",
        "arm/asm-offsets.h",
        "arm/audiodsp_arm.h",
        "arm/blockdsp_arm.h",
        "arm/cabac.h",
        "arm/dca.h",
        "arm/hevcdsp_arm.h",
        "arm/hpeldsp_arm.h",
        "arm/idct.h",
        "arm/idctdsp_arm.h",
        "arm/mathops.h",
        "arm/mpegvideo_arm.h",
        "arm/startcode.h",
        "arm/vc1dsp.h",
        "arm/videodsp_arm.h",
        "arm/vp8.h",
        "arm/vp8dsp.h",
        "arm/vp9dsp_init.h",
        "arm/vpx_arith.h",
        "ass.h",
        "ass_split.h",
        "asv.h",
        "atrac.h",
        "atrac1data.h",
        "atrac3data.h",
        "atrac3plus.h",
        "atrac3plus_data.h",
        "atrac9tab.h",
        "atsc_a53.h",
        "audio_frame_queue.h",
        "audiodsp.h",
        "av1.h",
        "av1_levels.h",
        "av1_parse.h",
        "av1dec.h",
        "avcodec.h",
        "avcodec_internal.h",
        "avdct.h",
        "avs2.h",
        "avs3.h",
        "bethsoftvideo.h",
        "bgmc.h",
        "binkdata.h",
        "binkdsp.h",
        "bintext.h",
        "bitstream.h",
        "bitstream_template.h",
        "blockdsp.h",
        "bmp.h",
        "bsf.h",
        "bsf_internal.h",
        "bswapdsp.h",
        "bytestream.h",
        "cabac.h",
        "cabac_functions.h",
        "canopus.h",
        "cavs.h",
        "cavsdsp.h",
        "cbrt_data.h",
        "cbrt_tablegen.h",
        "cbs.h",
        "cbs_apv.h",
        "cbs_av1.h",
        "cbs_bsf.h",
        "cbs_h264.h",
        "cbs_h2645.h",
        "cbs_h265.h",
        "cbs_h266.h",
        "cbs_internal.h",
        "cbs_jpeg.h",
        "cbs_mpeg2.h",
        "cbs_sei.h",
        "cbs_vp8.h",
        "cbs_vp9.h",
        "celp_filters.h",
        "celp_math.h",
        "cfhd.h",
        "cfhddsp.h",
        "cfhdencdsp.h",
        "cga_data.h",
        "clearvideodata.h",
        "codec.h",
        "codec2utils.h",
        "codec_desc.h",
        "codec_id.h",
        "codec_internal.h",
        "codec_par.h",
        "cookdata.h",
        "copy_block.h",
        "d3d11va.h",
        "d3d12va_decode.h",
        "d3d12va_encode.h",
        "dca.h",
        "dca_core.h",
        "dca_exss.h",
        "dca_lbr.h",
        "dca_sample_rate_tab.h",
        "dca_syncwords.h",
        "dca_xll.h",
        "dcaadpcm.h",
        "dcadata.h",
        "dcadct.h",
        "dcadec.h",
        "dcadsp.h",
        "dcaenc.h",
        "dcahuff.h",
        "dcamath.h",
        "dct.h",
        "dct32.h",
        "dctref.h",
        "decode.h",
        "decode_bsf.h",
        "defs.h",
        "dirac.h",
        "dirac_arith.h",
        "dirac_dwt.h",
        "dirac_vlc.h",
        "diracdsp.h",
        "diractab.h",
        "dnxhddata.h",
        "dnxhdenc.h",
        "dolby_e.h",
        "dovi_rpu.h",
        "dpx.h",
        "dsd.h",
        "dv.h",
        "dv_internal.h",
        "dv_profile.h",
        "dv_profile_internal.h",
        "dv_tablegen.h",
        "dvaudio.h",
        "dvbtxt.h",
        "dvdata.h",
        "dvdsub.h",
        "dxv.h",
        "dxva2.h",
        "dxva2_internal.h",
        "dynamic_hdr_vivid.h",
        "eac3_data.h",
        "eac3enc.h",
        "eaidct.h",
        "elbg.h",
        "elsdec.h",
        "encode.h",
        "error_resilience.h",
        "evc.h",
        "evc_parse.h",
        "evc_ps.h",
        "evrcdata.h",
        "executor.h",
        "exif.h",
        "exif_internal.h",
        "exrdsp.h",
        "faandct.h",
        "faanidct.h",
        "faxcompr.h",
        "fdctdsp.h",
        "ffjni.h",
        "fflcms2.h",
        "ffv1.h",
        "ffv1_vulkan.h",
        "ffv1enc.h",
        "fits.h",
        "flac.h",
        "flac_parse.h",
        "flacdata.h",
        "flacdsp.h",
        "flacencdsp.h",
        "flvdec.h",
        "flvenc.h",
        "fmtconvert.h",
        "frame_thread_encoder.h",
        "g722.h",
        "g722dsp.h",
        "g723_1.h",
        "g728data.h",
        "g729.h",
        "g729data.h",
        "g729postfilter.h",
        "get_bits.h",
        "gif.h",
        "golomb.h",
        "gsm.h",
        "gsmdec_data.h",
        "h261.h",
        "h261enc.h",
        "h263.h",
        "h263data.h",
        "h263dec.h",
        "h263dsp.h",
        "h263enc.h",
        "h264.h",
        "h2645_parse.h",
        "h2645_sei.h",
        "h2645_vui.h",
        "h2645data.h",
        "h264_levels.h",
        "h264_mvpred.h",
        "h264_parse.h",
        "h264_ps.h",
        "h264_sei.h",
        "h264chroma.h",
        "h264data.h",
        "h264dec.h",
        "h264dsp.h",
        "h264idct.h",
        "h264pred.h",
        "h264qpel.h",
        "h265_profile_level.h",
        "h274.h",
        "hap.h",
        "hashtable.h",
        "hca_data.h",
        "hevc/data.h",
        "hevc/dsp.h",
        "hevc/hevc.h",
        "hevc/hevcdec.h",
        "hevc/parse.h",
        "hevc/pred.h",
        "hevc/ps.h",
        "hevc/sei.h",
        "hpeldsp.h",
        "hq_common.h",
        "hq_hqadata.h",
        "hq_hqadsp.h",
        "hqxdsp.h",
        "hqxvlc.h",
        "htmlsubtitles.h",
        "huffman.h",
        "huffyuv.h",
        "huffyuvdsp.h",
        "huffyuvencdsp.h",
        "hw_base_encode.h",
        "hw_base_encode_h264.h",
        "hw_base_encode_h265.h",
        "hwaccel_internal.h",
        "hwaccels.h",
        "hwconfig.h",
        "idctdsp.h",
        "ilbcdata.h",
        "imcdata.h",
        "indeo2data.h",
        "indeo3data.h",
        "indeo4data.h",
        "indeo5data.h",
        "internal.h",
        "intrax8.h",
        "intrax8dsp.h",
        "intrax8huf.h",
        "itut35.h",
        "ivi.h",
        "ivi_dsp.h",
        "jacosub.h",
        "jni.h",
        "jpeg2000.h",
        "jpeg2000dec.h",
        "jpeg2000dsp.h",
        "jpeg2000dwt.h",
        "jpeg2000htdec.h",
        "jpegls.h",
        "jpeglsdec.h",
        "jpegquanttables.h",
        "jpegtables.h",
        "jpegtabs.h",
        "jpegxl.h",
        "jpegxl_parse.h",
        "jpegxs.h",
        "kbdwin.h",
        "lagarithrac.h",
        "lcevcdec.h",
        "lcl.h",
        "leaddata.h",
        "leb.h",
        "libaom.h",
        "libjxl.h",
        "libopenh264.h",
        "libopus.h",
        "libvpx.h",
        "libwebpenc_common.h",
        "loongarch/cabac.h",
        "loongarch/h264_intrapred_loongarch.h",
        "loongarch/h264chroma_loongarch.h",
        "loongarch/h264dsp_loongarch.h",
        "loongarch/h264qpel_loongarch.h",
        "loongarch/hevcdsp_lasx.h",
        "loongarch/hevcdsp_lsx.h",
        "loongarch/hpeldsp_lasx.h",
        "loongarch/idctdsp_loongarch.h",
        "loongarch/vc1dsp_loongarch.h",
        "loongarch/vp8dsp_loongarch.h",
        "loongarch/vp9dsp_loongarch.h",
        "lossless_audiodsp.h",
        "lossless_videodsp.h",
        "lossless_videoencdsp.h",
        "lpc.h",
        "lpc_functions.h",
        "lsp.h",
        "lzf.h",
        "lzw.h",
        "mathops.h",
        "me_cmp.h",
        "mediacodec.h",
        "mediacodec_surface.h",
        "mediacodec_sw_buffer.h",
        "mediacodec_wrapper.h",
        "mediacodecdec_common.h",
        "metasound_data.h",
        "metasound_twinvq_data.h",
        "mf_utils.h",
        "mips/amrwbdec_mips.h",
        "mips/blockdsp_mips.h",
        "mips/cabac.h",
        "mips/compute_antialias_fixed.h",
        "mips/compute_antialias_float.h",
        "mips/constants.h",
        "mips/h263dsp_mips.h",
        "mips/h264chroma_mips.h",
        "mips/h264dsp_mips.h",
        "mips/h264pred_mips.h",
        "mips/hevc_macros_msa.h",
        "mips/hevcdsp_mips.h",
        "mips/hevcpred_mips.h",
        "mips/hpeldsp_mips.h",
        "mips/idctdsp_mips.h",
        "mips/lsp_mips.h",
        "mips/mathops.h",
        "mips/me_cmp_mips.h",
        "mips/mpegvideo_mips.h",
        "mips/pixblockdsp_mips.h",
        "mips/qpeldsp_mips.h",
        "mips/vc1dsp_mips.h",
        "mips/vp3dsp_mips.h",
        "mips/vp8dsp_mips.h",
        "mips/vp9dsp_mips.h",
        "mips/wmv2dsp_mips.h",
        "mips/xvididct_mips.h",
        "mjpeg.h",
        "mjpegdec.h",
        "mjpegenc.h",
        "mjpegenc_common.h",
        "mjpegenc_huffman.h",
        "mlp.h",
        "mlp_parse.h",
        "mlpdsp.h",
        "mlz.h",
        "motion_est.h",
        "motionpixels_tablegen.h",
        "mpc.h",
        "mpc7data.h",
        "mpc8data.h",
        "mpc8huff.h",
        "mpcdata.h",
        "mpeg12.h",
        "mpeg12data.h",
        "mpeg12dec.h",
        "mpeg12enc.h",
        "mpeg12vlc.h",
        "mpeg4audio.h",
        "mpeg4audio_copy_pce.h",
        "mpeg4audio_sample_rates.h",
        "mpeg4data.h",
        "mpeg4video.h",
        "mpeg4videodata.h",
        "mpeg4videodec.h",
        "mpeg4videodefs.h",
        "mpeg4videodsp.h",
        "mpeg4videoenc.h",
        "mpeg_er.h",
        "mpegaudio.h",
        "mpegaudio_tablegen.h",
        "mpegaudiodata.h",
        "mpegaudiodec_common_tablegen.h",
        "mpegaudiodecheader.h",
        "mpegaudiodsp.h",
        "mpegaudiotab.h",
        "mpegaudiotabs.h",
        "mpegpicture.h",
        "mpegutils.h",
        "mpegvideo.h",
        "mpegvideo_unquantize.h",
        "mpegvideodata.h",
        "mpegvideodec.h",
        "mpegvideoenc.h",
        "mpegvideoencdsp.h",
        "mqc.h",
        "msgsmdec.h",
        "msmpeg4.h",
        "msmpeg4_vc1_data.h",
        "msmpeg4data.h",
        "msmpeg4dec.h",
        "msmpeg4enc.h",
        "msrledec.h",
        "mss12.h",
        "mss2dsp.h",
        "mss34dsp.h",
        "nellymoser.h",
        "nvdec.h",
        "nvenc.h",
        "ohcodec.h",
        "on2avcdata.h",
        "options_table.h",
        "opus/celt.h",
        "opus/dsp.h",
        "opus/enc.h",
        "opus/enc_psy.h",
        "opus/enc_utils.h",
        "opus/opus.h",
        "opus/parse.h",
        "opus/pvq.h",
        "opus/rc.h",
        "opus/silk.h",
        "opus/tab.h",
        "packet.h",
        "packet_internal.h",
        "paf.h",
        "parser.h",
        "parser_internal.h",
        "pcm_tablegen.h",
        "pixblockdsp.h",
        "pixels.h",
        "png.h",
        "pngdsp.h",
        "pnm.h",
        "ppc/fdct.h",
        "ppc/hpeldsp_altivec.h",
        "ppc/mathops.h",
        "profiles.h",
        "progressframe.h",
        "prores_raw.h",
        "proresdata.h",
        "proresdec.h",
        "proresdsp.h",
        "psymodel.h",
        "pthread_internal.h",
        "put_bits.h",
        "put_golomb.h",
        "qcelpdata.h",
        "qdm2_tablegen.h",
        "qdm2data.h",
        "qoi.h",
        "qpeldsp.h",
        "qsv.h",
        "qsv_internal.h",
        "qsvenc.h",
        "ra144.h",
        "ra288.h",
        "ralfdata.h",
        "rangecoder.h",
        "ratecontrol.h",
        "raw.h",
        "raw_pix_fmt_tags.h",
        "rectangle.h",
        "riscv/h26x/h2656dsp.h",
        "riscv/mathops.h",
        "riscv/vp8dsp.h",
        "riscv/vp9dsp.h",
        "rl.h",
        "rle.h",
        "rnd_avg.h",
        "roqvideo.h",
        "rtjpeg.h",
        "rv10dec.h",
        "rv10enc.h",
        "rv30data.h",
        "rv34.h",
        "rv34data.h",
        "rv34dsp.h",
        "rv34vlc.h",
        "rv40data.h",
        "rv40vlc2.h",
        "rv60data.h",
        "rv60dsp.h",
        "rv60vlcs.h",
        "sbc.h",
        "sbcdec_data.h",
        "sbcdsp.h",
        "sbcdsp_data.h",
        "sbr.h",
        "sbrdsp.h",
        "scpr.h",
        "scpr3.h",
        "sei.h",
        "sgi.h",
        "sheervideodata.h",
        "simple_idct.h",
        "sinewin.h",
        "sinewin_fixed_tablegen.h",
        "sinewin_tablegen.h",
        "sipr.h",
        "sipr16kdata.h",
        "siprdata.h",
        "smpte_436m.h",
        "smpte_436m_internal.h",
        "snappy.h",
        "snow.h",
        "snow_dwt.h",
        "snowdata.h",
        "sp5x.h",
        "speedhq.h",
        "speedhqenc.h",
        "speexdata.h",
        "startcode.h",
        "sunrast.h",
        "svq1.h",
        "svq1_cb.h",
        "svq1_vlc.h",
        "svq1enc_cb.h",
        "svq1encdsp.h",
        "synth_filter.h",
        "tableprint.h",
        "tableprint_vlc.h",
        "tak.h",
        "takdsp.h",
        "targa.h",
        "texturedsp.h",
        "thread.h",
        "threadframe.h",
        "threadprogress.h",
        "tiff.h",
        "tiff_common.h",
        "tiff_data.h",
        "to_upper4.h",
        "tpeldsp.h",
        "truemotion1data.h",
        "truespeech_data.h",
        "tscc2data.h",
        "ttadata.h",
        "ttadsp.h",
        "ttaencdsp.h",
        "ttmlenc.h",
        "twinvq.h",
        "twinvq_data.h",
        "ulti_cb.h",
        "unary.h",
        "utvideo.h",
        "utvideodsp.h",
        "v210dec.h",
        "v210dec_init.h",
        "v210enc.h",
        "v210enc_init.h",
        "v4l2_buffers.h",
        "v4l2_context.h",
        "v4l2_fmt.h",
        "v4l2_m2m.h",
        "vaapi_decode.h",
        "vaapi_encode.h",
        "vaapi_hevc.h",
        "vbn.h",
        "vc1.h",
        "vc1_common.h",
        "vc1_pred.h",
        "vc1_vlc_data.h",
        "vc1acdata.h",
        "vc1data.h",
        "vc1dsp.h",
        "vc2enc_dwt.h",
        "vdpau.h",
        "vdpau_internal.h",
        "version.h",
        "version_major.h",
        "videodsp.h",
        "videotoolbox.h",
        "vlc.h",
        "vorbis.h",
        "vorbis_data.h",
        "vorbis_enc_data.h",
        "vorbis_parser.h",
        "vorbis_parser_internal.h",
        "vorbisdsp.h",
        "vp3data.h",
        "vp3dsp.h",
        "vp4data.h",
        "vp56.h",
        "vp56data.h",
        "vp56dsp.h",
        "vp5data.h",
        "vp6data.h",
        "vp8.h",
        "vp89_rac.h",
        "vp8data.h",
        "vp8dsp.h",
        "vp9.h",
        "vp9data.h",
        "vp9dec.h",
        "vp9dsp.h",
        "vp9shared.h",
        "vpx_rac.h",
        "vt_internal.h",
        "vulkan_decode.h",
        "vulkan_encode.h",
        "vulkan_video.h",
        "vvc.h",
        "vvc/cabac.h",
        "vvc/ctu.h",
        "vvc/data.h",
        "vvc/dec.h",
        "vvc/dsp.h",
        "vvc/filter.h",
        "vvc/inter.h",
        "vvc/intra.h",
        "vvc/itx_1d.h",
        "vvc/mvs.h",
        "vvc/ps.h",
        "vvc/refs.h",
        "vvc/sei.h",
        "vvc/thread.h",
        "wasm/hevc/idct.h",
        "wasm/hevc/sao.h",
        "wavpack.h",
        "wavpackenc.h",
        "wma.h",
        "wma_common.h",
        "wma_freqs.h",
        "wmadata.h",
        "wmaprodata.h",
        "wmavoice_data.h",
        "wmv2.h",
        "wmv2data.h",
        "wmv2dec.h",
        "wmv2dsp.h",
        "x86/cabac.h",
        "x86/constants.h",
        "x86/fdct.h",
        "x86/fpel.h",
        "x86/h26x/h2656dsp.h",
        "x86/hevc/dsp.h",
        "x86/hpeldsp.h",
        "x86/idctdsp.h",
        "x86/mathops.h",
        "x86/qpel.h",
        "x86/simple_idct.h",
        "x86/vc1dsp.h",
        "x86/vp9dsp_init.h",
        "x86/vpx_arith.h",
        "x86/xvididct.h",
        "xface.h",
        "xiph.h",
        "xvididct.h",
        "xwd.h",
        "zlib_wrapper.h",
    ] + [":avcodec_asm_clean"],
    copts = CC_COPTS,
    includes = [
        ".",
        "..",
        "../platform/common/libavcodec",
        "aarch64",
        "//libavcodec",
    ],
    linkopts = select({
        "//:darwin_aarch64": [
            "-liconv",
            "-framework CoreVideo",
            "-framework CoreMedia",
            "-framework VideoToolbox",
            "-framework CoreFoundation",
        ],
        "//conditions:default": [],
    }),
    linkstatic = True,
    textual_hdrs = [
        "aac/aacdec_dsp_template.c",
        "aac/aacdec_proc_template.c",
        "aacpsdsp_template.c",
        "aacps_tablegen_template.c",
        "aacpsdata.c",
        "aacsbr_template.c",
        "aarch64/vp9dsp_init_16bpp_aarch64_template.c",
        "aarch64/vvc/alf_template.c",
        "ac3enc_template.c",
        "aom_film_grain_template.c",
        "apv_entropy.c",
        "arm/vp9dsp_init_16bpp_arm_template.c",
        "bit_depth_template.c",
        "//platform/common/libavcodec:bsf_list.c",
        "cabac.c",
        "cbrt_tablegen_template.c",
        "cbs_apv_syntax_template.c",
        "cbs_av1_syntax_template.c",
        "cbs_h264_syntax_template.c",
        "cbs_h265_syntax_template.c",
        "cbs_h266_syntax_template.c",
        "cbs_jpeg_syntax_template.c",
        "cbs_mpeg2_syntax_template.c",
        "cbs_sei_syntax_template.c",
        "cbs_vp8_syntax_template.c",
        "cbs_vp9_syntax_template.c",
        "//platform/common/libavcodec:codec_list.c",
        "dct32_template.c",
        "dirac_dwt_template.c",
        "ffv1dec_template.c",
        "ffv1enc_template.c",
        "ffv1_template.c",
        "flacdsp_lpc_template.c",
        "flacdsp_template.c",
        "g728_template.c",
        "gsmdec_template.c",
        "h264addpx_template.c",
        "h264chroma_template.c",
        "h264dsp_template.c",
        "h264idct_template.c",
        "h264_mb_template.c",
        "h264_mc_template.c",
        "h264pred_template.c",
        "h264qpel_template.c",
        "h26x/h2656_deblock_template.c",
        "h26x/h2656_inter_template.c",
        "h26x/h2656_sao_template.c",
        "hevc/dsp_template.c",
        "hevc/pred_template.c",
        "hpel_template.c",
        "htmlsubtitles.c",
        "jfdctint_template.c",  # libjpeg
        "jpeg2000dwt.c",
        "mjpegenc_huffman.c",
        "motion_est_template.c",
        "mpegaudiodec_template.c",
        "mpegaudiodsp_template.c",
        "//platform/common/libavcodec:parser_list.c",
        "pel_template.c",
        "ppc/h264chroma_template.c",
        "ppc/h264qpel_template.c",
        "ppc/hevcdsp_template.c",
        "proresdsp.c",
        "qpel_template.c",
        "sbrdsp_template.c",
        "simple_idct_template.c",
        "snowenc.c",
        "tests/bitstream_template.c",
        "texturedsp_template.c",
        "v210_template.c",
        "videodsp_template.c",
        "vp9dsp_template.c",
        "vp9_mc_template.c",
        "vvc/dsp_template.c",
        "vvc/filter_template.c",
        "vvc/inter_template.c",
        "vvc/intra_template.c",
        "x86/mpegvideoenc_template.c",
        "x86/vp9dsp_init_16bpp_template.c",
        "//libavutil:file_open.c",
        "//libavutil:float2half.c",
        "//libavutil:float_scalarproduct.c",
        "//libavutil:half2float.c",
        "//libavutil:log2_tab.c",
        "//libavutil:reverse.c",
        "//libavutil:riscv/cpu_common.c",
        "//libavutil:timecode_internal.c",
        "//libavutil:vulkan.c",
        "//libavutil:vulkan_glslang.c",
        "//libavutil:vulkan_shaderc.c",
        "x86/h264_cabac.c",
        "aarch64/neon.S",
    ],
    deps = [
        "//:compat",
        "//:config_h",
        "//:ffmpeg_private_headers",
        "//libavutil:avutil",
        "//libswresample:swresample",
        "@libvpx",
        "@opus",
        "@x264",
    ],
)

ffmpeg_cc_test(
    name = "avcodec_test",
    srcs = ["tests/avcodec.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "avpacket_test",
    srcs = ["tests/avpacket.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "bitstream_be_test",
    srcs = ["tests/bitstream_be.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "bitstream_le_test",
    srcs = ["tests/bitstream_le.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "codec_desc_test",
    srcs = ["tests/codec_desc.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "htmlsubtitles_test",
    srcs = ["tests/htmlsubtitles.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "jpeg2000dwt_test",
    srcs = ["tests/jpeg2000dwt.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "mathops_test",
    srcs = ["tests/mathops.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "cabac_test",
    srcs = ["tests/cabac.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "celp_math_test",
    srcs = ["tests/celp_math.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "golomb_test",
    srcs = ["tests/golomb.c"],
    deps = [":avcodec"],
)

ffmpeg_cc_test(
    name = "rangecoder_test",
    srcs = ["tests/rangecoder.c"],
    deps = [":avcodec"],
)
