load("@rules_cc//cc:defs.bzl", "cc_library")
load("//:ffmpeg.bzl", "CC_COPTS", "ffmpeg_cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "avformat",
    srcs = [
        "ac3_channel_layout_tab.c",
        "allformats.c",
        "av1.c",
        "avformat.c",
        "avio.c",
        "aviobuf.c",
        "avlanguage.c",
        "codecstring.c",
        "demux.c",
        "demux_utils.c",
        "dovi_isom.c",
        "dump.c",
        "dv.c",
        "dvdclut.c",
        "fifo.c",
        "file.c",
        "flac_picture.c",
        "format.c",
        "gif.c",
        "iamf.c",
        "iamf_parse.c",
        "iamf_reader.c",
        "id3v1.c",
        "id3v2.c",
        "isom.c",
        "isom_tags.c",
        "log2_tab.c",
        "matroska.c",
        "matroskadec.c",
        "matroskaenc.c",
        "metadata.c",
        "mov.c",
        "mov_chan.c",
        "mov_esds.c",
        "mpeg4audio_sample_rates.c",
        "mpegaudiotabs.c",
        "mux.c",
        "mux_utils.c",
        "nal.c",
        "network.c",
        "oggparsevorbis.c",
        "options.c",
        "os_support.c",
        "protocols.c",
        "qtpalette.c",
        "replaygain.c",
        "riff.c",
        "riffdec.c",
        "rmsipr.c",
        "sdp.c",
        "seek.c",
        "srtp.c",
        "to_upper4.c",
        "url.c",
        "urldecode.c",
        "utils.c",
        "version.c",
        "vorbiscomment.c",
        "vpcc.c",
    ] + [],
    hdrs = [
        "aiff.h",
        "apetag.h",
        "apv.h",
        "argo_asf.h",
        "asf.h",
        "asfcrypt.h",
        "ast.h",
        "av1.h",
        "avc.h",
        "avformat.h",
        "avformat_internal.h",
        "avi.h",
        "avio.h",
        "avio_internal.h",
        "avlanguage.h",
        "caf.h",
        "cbs.h",
        "dash.h",
        "demux.h",
        "dovi_isom.h",
        "dv.h",
        "dvdclut.h",
        "evc.h",
        "ffmeta.h",
        "flac_picture.h",
        "flacenc.h",
        "flv.h",
        "gxf.h",
        "hevc.h",
        "hls_sample_encryption.h",
        "hlsplaylist.h",
        "http.h",
        "httpauth.h",
        "iamf.h",
        "iamf_parse.h",
        "iamf_reader.h",
        "iamf_writer.h",
        "id3v1.h",
        "id3v2.h",
        "imf.h",
        "img2.h",
        "internal.h",
        "ip.h",
        "ircam.h",
        "isom.h",
        "lrc.h",
        "matroska.h",
        "metadata.h",
        "mms.h",
        "mov_chan.h",
        "movenc.h",
        "movenc_ttml.h",
        "movenccenc.h",
        "mpeg.h",
        "mpegts.h",
        "mux.h",
        "mxf.h",
        "nal.h",
        "network.h",
        "nut.h",
        "oggdec.h",
        "oma.h",
        "options_table.h",
        "os_support.h",
        "pcm.h",
        "qtpalette.h",
        "rawdec.h",
        "rawenc.h",
        "rawutils.h",
        "rdt.h",
        "replaygain.h",
        "riff.h",
        "rm.h",
        "rmsipr.h",
        "rso.h",
        "rtmp.h",
        "rtmpcrypt.h",
        "rtmpdh.h",
        "rtmppkt.h",
        "rtp.h",
        "rtp_av1.h",
        "rtpdec.h",
        "rtpdec_formats.h",
        "rtpenc.h",
        "rtpenc_chain.h",
        "rtpproto.h",
        "rtsp.h",
        "rtspcodes.h",
        "sauce.h",
        "smjpeg.h",
        "sox.h",
        "spdif.h",
        "srtp.h",
        "subtitles.h",
        "swf.h",
        "tee_common.h",
        "tls.h",
        "ttmlenc.h",
        "url.h",
        "urldecode.h",
        "version.h",
        "version_major.h",
        "voc.h",
        "vorbiscomment.h",
        "vpcc.h",
        "vvc.h",
        "w64.h",
        "wtv.h",
        "wv.h",
        "yuv4mpeg.h",
    ],
    copts = CC_COPTS,
    includes = [
        ".",
        "../platform/common",
    ],
    linkopts = select({
        "//:windows_x86_64": [
            "-DEFAULTLIB:ws2_32.lib",
            "-DEFAULTLIB:shell32.lib",
        ],
        "//conditions:default": [],
    }),
    linkstatic = True,
    textual_hdrs = [
        "//libavutil:file_open.c",
        "//libavutil:float2half.c",
        "//libavutil:float_scalarproduct.c",
        "//libavutil:half2float.c",
        "//libavutil:log2_tab.c",
        "//libavutil:reverse.c",
        "//libavutil:riscv/cpu_common.c",
        "//libavutil:timecode_internal.c",
        "//libavutil:vulkan.c",
        "//libavutil:vulkan_glslang.c",
        "//libavutil:vulkan_shaderc.c",
        "//platform/common/libavformat:demuxer_list.c",
        "fifo.c",
        "imf_cpl.c",
        "imfdec.c",
        "//platform/common/libavformat:muxer_list.c",
        "//platform/common/libavformat:protocol_list.c",
        "rtmpdh.c",
    ],
    deps = [
        "//:compat",
        "//:config_h",
        "//:ffmpeg_headers",
        "//:ffversion_common_h",
        "//libavcodec:avcodec",
        "//libavutil:avutil",
    ],
)

# ffmpeg_cc_test(
#     name = "seek_test",
#     srcs = ["tests/seek.c"],
#     deps = [":avformat"],
# )

ffmpeg_cc_test(
    name = "url_test",
    srcs = ["tests/url.c"],
    deps = [":avformat"],
)

# ffmpeg_cc_test(
#     name = "rtmpdh_test",
#     srcs = ["tests/rtmpdh.c"],
#     deps = [":avformat"],
# )

ffmpeg_cc_test(
    name = "noproxy_test",
    srcs = ["tests/noproxy.c"],
    deps = [":avformat"],
)

ffmpeg_cc_test(
    name = "srtp_test",
    srcs = ["tests/srtp.c"],
    deps = [":avformat"],
)

# ffmpeg_cc_test(
#     name = "fifo_muxer_test",
#     srcs = ["tests/fifo_muxer.c"],
#     deps = [":avformat"],
# )

# ffmpeg_cc_test(
#     name = "imf_test",
#     srcs = ["tests/imf.c"],
#     deps = [":avformat"],
# )

# ffmpeg_cc_test(
#     name = "movenc_test",
#     srcs = ["tests/movenc.c"],
#     deps = [":avformat"],
# )
