/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2026-01-26-714152dd9a"
#endif /* AVUTIL_FFVERSION_H */
